apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cve-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - su24.csye7125.t12.io
  resources:
  - githubreleasemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - su24.csye7125.t12.io
  resources:
  - githubreleasemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - su24.csye7125.t12.io
  resources:
  - githubreleasemonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - su24.csye7125.t12.io
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - su24.csye7125.t12.io
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - su24.csye7125.t12.io
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
