apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cve-operator
  name: cve-operator-controller-manager
  namespace: cve-operator
